---
# playbook.yml
- name: Display Host Variables for Targeted Servers
  hosts: all # This targets all hosts in your inventory. You can change this to a specific group, e.g., 'webservers'.
  gather_facts: yes # 'gather_facts' collects useful variables about the remote systems (like IP addresses, OS, memory, etc.)

  tasks:
    - name: 1. Display ALL variables for each host
      # This task iterates through each host in the play and prints all variables
      # associated with it. This includes inventory variables, facts, and registered variables.
      # The output can be very long, but it is comprehensive.
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 1 # Makes the output a bit cleaner and more readable by default.

    - name: 2. Display a SPECIFIC variable for each host (Example: Default IP Address)
      # Often, you don't need all variables, just one.
      # This example prints the default IPv4 address for each host.
      # The 'when' condition prevents an error if the host doesn't have this fact.
      debug:
        msg: "The default IPv4 address for '{{ inventory_hostname }}' is: {{ ansible_default_ipv4.address }}"
      when: ansible_default_ipv4.address is defined

    - name: 3. Display another SPECIFIC variable (Example: Memory)
      # Here is another example, this time showing the total memory in MB.
      debug:
        msg: "Total memory for '{{ inventory_hostname }}' is: {{ ansible_memtotal_mb }} MB"
      when: ansible_memtotal_mb is defined