---
# playbook.yml
- name: Display Host Variables for Targeted Servers
  hosts: all # This targets all hosts in your inventory. You can change this to a specific group, e.g., 'webservers'.
  gather_facts: false # 'gather_facts' collects useful variables about the remote systems (like IP addresses, OS, memory, etc.)

  tasks:
    - name: 1. Display ALL variables for each host
      # This task iterates through each host in the play and prints all variables
      # associated with it. This includes inventory variables, facts, and registered variables.
      # The output can be very long, but it is comprehensive.
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
        verbosity: 1 # Makes the output a bit cleaner and more readable by default.
    - name: Add inventory
      delegate_to: localhost
      run_once: true
      ansible.controller.inventory:
        name: "failed Inventory"
        description: "failed Inventory"
        organization: "Default"
        state: present

    - name: Add host
      ansible.controller.host:
        name: "{{ hostvars[inventory_hostname].name }}-faild"
        # description: "Local Host Group"
        inventory: "failed Inventory"
        state: present
        # controller_config_file: "~/tower_cli.cfg"
        variables:
          "{{ hostvars[inventory_hostname].variables }}"