---
# playbook.yml
- name: Copy host data to another inventory
  hosts: all 
  gather_facts: false 

  tasks:
    - name: Display ALL variables for each host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
        verbosity: 1
    - name: Add inventory
      delegate_to: localhost
      run_once: true
      ansible.controller.inventory:
        name: "failed hosts Inventory"
        description: "failed Inventory"
        organization: "Default"
        state: present

    - name: Add host
      delegate_to: localhost
      ansible.controller.host:
        name: "{{ hostvars[inventory_hostname].name }}-failed"
        # description: "Local Host Group"
        inventory: "failed Inventory"
        state: present
        # controller_config_file: "~/tower_cli.cfg"
        variables: "{{ hostvars[inventory_hostname] }}"