---
- name: Gather pending updates from Azure Update Manager
  hosts: localhost
  gather_facts: false
  vars:
    subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    resource_group: "openenv-ql5sw"
    catalog_name: "Microsoft monthly"
    
  tasks:
    - name: Get list of VMs
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        subscription_id: "{{ subscription_id }}"
      register: vm_facts

    - name: Display VM names
      ansible.builtin.debug:
        var: vm_facts.vms

    - name: Run Azure CLI command to get pending updates
      ansible.builtin.command: |
        az vm update check --resource-group {{ resource_group }} --name {{ item.name }}
      loop: "{{ vm_facts.vms }}"
      register: pending_updates

    - name: Display pending updates
      ansible.builtin.debug:
        var: item.stdout
  