---
- name: Patch Azure Windows VM
  hosts: all
  tasks:
    - name: Install Windows updates
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        reboot: true
      register: update_result
    - name: Display update results
      ansible.builtin.debug:
        var: update_result
