---
- name: Create snapshots
  hosts: ssh-test # <<< IMPORTANT: Replace 'your_windows_group' with your actual inventory group name (e.g., 'windows_servers')
  # gather_facts: false
 
  tasks:

    - name: test ssh connection
      ansible.builtin.shell:
        cmd: ls -lrt
