---
- name: "Definitive Timezone Diagnostic Playbook"
  hosts: localhost
  gather_facts: true
  connection: local

  tasks:
    - name: "Time date"
      debug:
        msg: "Current time: {{ ansible_date_time.iso8601_basic_short }}"

    - name: Display original UTC time from Ansible facts
      ansible.builtin.debug:
        msg: "Current UTC time (from facts): {{ ansible_date_time.iso8601 }}"

    - name: ISO 8601 datetime in local timezone
      ansible.builtin.debug:
        msg: "epicrpt-{{ lookup('pipe', 'TZ=US/Central date +%Y%m%dT%H%M%S') }}-val"
    
    - name: Eastern time zone
      ansible.builtin.debug:
        msg: "epicrpt-{{ lookup('pipe', 'TZ=US/Eastern date +%Y%m%dT%H%M%S') }}-val"
        # US/Eastern
    - name: Using Epoch
      ansible.builtin.debug:
        msg: "{{ '%Y%m%dT%H%M%S' | strftime(ansible_date_time.epoch | int) }}"
