---
- name: "Definitive Timezone Diagnostic Playbook"
  hosts: localhost
  gather_facts: true
  connection: local

  tasks:
    - name: "Time date"
      debug:
        msg: "Current time: {{ ansible_date_time.iso8601_basic_short }}"

    - name: Display original UTC time from Ansible facts
      ansible.builtin.debug:
        msg: "Current UTC time (from facts): {{ ansible_date_time.iso8601 }}"


    - name: Convert current UTC time to another timezone (US/Pacific)
      ansible.builtin.debug:
        msg: >-
          The current time in Pacific Time is
          {{ ansible_date_time.iso8601 | to_datetime | strftime('%Y-%m-%d %I:%M:%S', 'US/Central') }}.
