---
- name: "Definitive Timezone Diagnostic Playbook"
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: "Time date"
      debug:
        msg: "Current time: {{ ansible_date_time.iso8601_basic_short }}"
