---
- name: "Final Confirmation Playbook"
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: "Run the now() function with a timezone"
      debug:
        msg: "SUCCESS: The time in Chicago is {{ now(tz='America/Chicago', fmt='%Y-%m-%d %H:%M:%S') }}"