---
- name: Query Azure Update Manager for Pending Updates via REST API
  hosts: localhost # This playbook runs on the Ansible control node (or execution node)
  connection: local # It performs actions locally, querying Azure API

  vars:
    # Azure authentication details - these are typically populated by AAP's Azure Resource Manager credential
    # when assigned to the job template. Ensure your AAP credential is configured to pass these.
    azure_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    azure_client_secret: "{{ lookup('env', 'AZURE_SECRET') }}"
    azure_tenant_id: "{{ lookup('env', 'AZURE_TENANT') }}"
    # azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}" # Not directly used in ARG query body, but often available

    # Azure AD token endpoint for client credentials flow
    azure_token_url: "https://login.microsoftonline.com/{{ azure_tenant_id }}/oauth2/token"
    azure_resource_uri: "https://management.azure.com/" # The resource/audience for the token

    # Azure Resource Graph API endpoint
    # The API version for Resource Graph queries.
    arg_api_url: "https://management.azure.com/providers/Microsoft.ResourceGraph/resources?api-version=2021-03-01"

    # Kusto Query Language (KQL) query to get pending software patches.
    # This query fetches individual pending patches (KB IDs for Windows) from Azure Resource Graph.
    # It assumes the machines are managed by Azure Update Manager and their assessments are in ARG.
    kql_query: |
      patchassessmentresources
      | where type has "softwarepatches" // Filter for individual software patch records
      | extend properties = parse_json(properties)
      | extend machineName = tostring(split(id, "/", 8)) // Extract machine name from resource ID
      | extend kbId = properties.kbId // Windows Knowledge Base ID
      | extend patchName = properties.patchName // Name of the patch
      | extend classification = properties.classification // Update classification (e.g., SecurityUpdates, CriticalUpdates)
      | extend rebootRequired = properties.rebootRequired // Indicates if a reboot is required
      | where isnull(properties.installationState) or properties.installationState == "Pending" // Filter for updates that are pending installation
      | project machineName, patchName, kbId, classification, rebootRequired // Select relevant fields for output

  tasks:
    - name: Get OAuth2 token from Azure AD
      ansible.builtin.uri:
        url: "{{ azure_token_url }}"
        method: POST
        body_format: form-urlencoded
        headers:
          Content-Type: "application/x-www-form-urlencoded" # Required for token endpoint
        body:
          grant_type: client_credentials
          client_id: "{{ azure_client_id }}"
          client_secret: "{{ azure_client_secret }}"
          resource: "{{ azure_resource_uri }}"
        status_code: 200
       # validate_certs: true
      register: azure_auth_token_response
      # no_log: true # Prevent sensitive token from being logged
      changed_when: false

    - name: Set access token fact
      ansible.builtin.set_fact:
        access_token: "{{ azure_auth_token_response.json.access_token }}"
      # no_log: true # Prevent sensitive token from being logged

    - name: Query Azure Resource Graph for pending updates via REST API
      ansible.builtin.uri:
        url: "{{ arg_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ access_token }}" # Use the obtained access token here
        body_format: json
        body:
          query: "{{ kql_query }}"
          # Optionally, you can specify target subscriptions or management groups for the query.
          # If not specified, the query runs against all subscriptions accessible by the service principal.
          # subscriptions:
          #   - "{{ azure_subscription_id }}"
        status_code: 200
        validate_certs: true
      register: azure_query_result
      changed_when: false

    - name: Parse Azure query result
      ansible.builtin.set_fact:
        pending_updates_data: "{{ azure_query_result.json }}"

    - name: Display summary of pending updates
      ansible.builtin.debug:
        msg: "--- Pending Updates Summary --- {{ azure_query_result }}"

    - name: Group updates by machine and display
      ansible.builtin.debug:
        msg: |
          Machine: {{ item.0 }}
            Updates:
          {% for update in item.1 %}
              - Name: {{ update.patchName }} (KB: {{ update.kbId }})
                Classification: {{ update.classification }}
                Reboot Required: {{ 'Yes' if update.rebootRequired else 'No' }}
          {% endfor %}
      loop: "{{ pending_updates_data.data | groupby('machineName') }}"
      loop_control:
        label: "{{ item.0 }}"
      when: pending_updates_data.data | length > 0

    - name: Inform if no pending updates found
      ansible.builtin.debug:
        msg: "No pending updates found via Azure Update Manager."
      when: pending_updates_data.data | length == 0
# --- NEW PLAY: Apply updates on existing Windows Servers from inventory (Phase 2: Remote Hosts) ---
- name: Apply updates on existing Windows Servers
  hosts: windows # <<< IMPORTANT: Replace 'your_windows_group' with your actual inventory group name (e.g., 'windows_servers')
  connection: winrm
  gather_facts: false # Optional, can speed up if facts aren't strictly needed

  # Ensure this play only runs if there were any machines with pending updates found in Phase 1
  # when: hostvars['localhost']['all_pending_updates_data'] is defined and hostvars['localhost']['all_pending_updates_data'] | length > 0

  vars:
    # Windows Machine Credential details - these need to be accessible for the remote hosts
    # It's recommended to configure these as environment variables in your AAP Job Template
    # using sensitive variables from your Windows Machine Credential, or directly in inventory.
    # If using inventory vars, remove these from here.
    # ansible_user: "{{ lookup('env', 'ANSIBLE_WINDOWS_USER') | default('thussein') }}"
    # ansible_password: "{{ lookup('env', 'ANSIBLE_WINDOWS_PASSWORD') }}"
    # ansible_port: 5986 # Use 5985 for HTTP WinRM
    # ansible_winrm_transport: ntlm # Use 'ntlm' for HTTP or if CredSSP isn't configured
    # # WARNING: For production, configure proper certificate validation instead of ignoring
    # ansible_winrm_server_cert_validation: ignore # Adjust for production

  tasks:
    - name: Get pending updates for the current host from the collected data
      ansible.builtin.set_fact:
        # Filter all_pending_updates_data for updates specific to the current inventory_hostname
        current_host_updates: >
          {{ hostvars['localhost']['all_pending_updates_data'] | selectattr('machineName', 'equalto', inventory_hostname) | list }}
        current_host_kb_ids: >
          {{ hostvars['localhost']['all_pending_updates_data'] | selectattr('machineName', 'equalto', inventory_hostname) | map(attribute='kbId') | list }}
        current_host_reboot_required: >
          {{ (hostvars['localhost']['all_pending_updates_data'] | selectattr('machineName', 'equalto', inventory_hostname) | selectattr('rebootRequired', 'equalto', true) | list) | length > 0 }}

    - name: Display pending updates for {{ inventory_hostname }}
      ansible.builtin.debug:
        msg: |
          Pending updates for {{ inventory_hostname }}:
          {% for update in current_host_updates %}
              - Name: {{ update.patchName }} (KB: {{ update.kbId }})
                Classification: {{ update.classification }}
                Reboot Required: {{ 'Yes' if update.rebootRequired else 'No' }}
          {% endfor %}
      when: current_host_updates | length > 0

    - name: Inform if no updates found for this specific host
      ansible.builtin.debug:
        msg: "No pending updates found for {{ inventory_hostname }} from Azure Update Manager data."
      when: current_host_updates | length == 0

    - name: Install specific Windows updates by KB ID
      ansible.windows.win_updates:
        kb_ids: "{{ current_host_kb_ids }}" # Use the KB IDs specific to this host
        state: installed
        reboot: false # Let win_reboot handle the reboot if required
      register: install_results
      when: current_host_kb_ids | length > 0

    - name: Perform reboot if required by updates
      ansible.windows.win_reboot:
        reboot_timeout: 600 # Wait up to 10 minutes for the server to reboot
      when: install_results.reboot_required or current_host_reboot_required

    - name: Inform if no specific KB IDs were installed for this machine
      ansible.builtin.debug:
        msg: "No specific KB IDs were provided for installation on {{ inventory_hostname }} or no updates were installed by win_updates."
      when: current_host_kb_ids | length == 0 or not install_results.changed
