---
- name: Get available updates from Azure Update Manager for a Windows VM
  hosts: localhost
  gather_facts: no
  vars:
    client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    secret: "{{ lookup('env', 'AZURE_SECRET') }}"
    tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
    subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    resource_group: "openenv-ql5sw"
    vm_name: "win-aap-test"
    api_version: "2023-11-01-preview"

  tasks:
    - name: Get access token from Azure AD
      uri:
        url: "https://login.microsoftonline.com/{{ tenant }}/oauth2/token"
        method: POST
        body:
          grant_type: client_credentials
          client_id: "{{ client_id }}"
          client_secret: "{{ secret }}"
          resource: https://management.azure.com/
        body_format: form-urlencoded
        headers:
          Content-Type: application/x-www-form-urlencoded
      register: azure_auth

    - name: Set the Azure auth token
      set_fact:
        access_token: "{{ azure_auth.json.access_token }}"

    - name: Get list of pending updates for Windows VM
      uri:
        url: "https://management.azure.com/subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Maintenance/updateConfigurations/{{ vm_name }}?api-version={{ api_version }}"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: application/json
      register: update_result

    - name: Print update details
      debug:
        msg: "{{ update_result.json }}"
