---
- name: VMware VM Snapshot Playbook for AAP
  hosts: windows2019srv_64Guest
  connection: local
  gather_facts: no
  vars_files:
    - vmware-cred.yml
  vars:
    vcenter_hostname: "{{ m-vmware-host }}"
    vm_name: "{{ hostvars[inventory_hostname].name }}"
    snapshot_description: "Pre-maintenance snapshot taken with Ansible"

  tasks:
    - name: Debug the vcenter_hostname variable
      ansible.builtin.debug:
        msg: "vcenter_hostname is: {{ vcenter_hostname }} and its type is: {{ vcenter_hostname | type_debug }}"
      ignore_errors: true # Use this in case printing the variable itself is the source of the error

# Your original failing task would be here...
    - name: "Create a snapshot for the VM: {{ vm_name }}"
      # This module manages VMware guest snapshots.
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ m-vmware-uname }}"
        password: "{{ m-vmware-pass }}"
        validate_certs: false

        name: "{{ vm_name }}"
        state: present

        # Snapshot Specifics
        snapshot_name: "ansible-snapshot-{{ ansible_date_time.iso8601 }}" # Creates a unique name with a timestamp
        description: "{{ snapshot_description }}"
        quiesce: true
        memory_snapshot: true
      register: snapshot_result
      no_log: false

    - name: "Display snapshot creation result"
      ansible.builtin.debug:
        msg: "Snapshot task completed for {{ vm_name }}. Result: {{ snapshot_result.msg }}"