---
- name: VMware VM Snapshot Playbook for AAP
  hosts: windows2019srv_64Guest
  connection: local
  gather_facts: no
  vars_files:
    - vmware-cred.yml
  vars:
    vcenter_hostname: "{{ m_vmware_host }}"
    vm_name: "{{ hostvars[inventory_hostname].name }}"
    snapshot_description: "Pre-maintenance snapshot taken with Ansible"
    date_time: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"

  tasks:
    - name: Debug the vcenter_hostname variable
      ansible.builtin.debug:
        msg: "vcenter_hostname is: {{ vcenter_hostname }} and its type is: {{ vcenter_hostname | type_debug }}"
      ignore_errors: true # Use this in case printing the variable itself is the source of the error
    - debug:
        var: hostvars[inventory_hostname]

# Your original failing task would be here...
    - name: "Create a snapshot for the VM: {{ vm_name }}"
      # This module manages VMware guest snapshots.
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ m_vmware_host }}"
        username: "{{ m_vmware_uname }}"
        password: "{{ m_vmware_pass }}"
        datacenter: "{{ m_datacenter_name }}"
        folder: "/{{ m_datacenter_name }}/vm/"
        validate_certs: false

        uuid: "{{ hostvars[inventory_hostname].config.uuid }}"
        state: present

        # Snapshot Specifics
        snapshot_name: "{{ hostvars[inventory_hostname].config.guestId }} _ {{ date_time }}" # Creates a unique name with a timestamp
        description: "{{ snapshot_description }}"
        quiesce: true
        # memory_snapshot: true
      delegate_to: localhost
      register: snapshot_result
      no_log: false

    - name: "Display snapshot creation result"
      ansible.builtin.debug:
        msg: "Snapshot task completed for {{ vm_name }}. Result: {{ snapshot_result}}"